- name: My first play
  hosts: demoservers
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world
   - name: Create file
     shell: echo "I'm ansible" > hoge.txt
   - name: Install OpenJDK
     ansible.builtin.apt:
       name: openjdk-17-jdk
       update_cache: yes
     become: true

